steps:
  - label: "Example Test"
    command: | 
        echo "Hello!"
        echo "check Hey from line 2"
  - wait

steps:
  - label: "Second build"
  - command: echo "Did we really reached here? :)"
  

