steps:
  - label: "Example Test"
    command: | 
        A = 4
        echo $4
        echo "Hello!"
        echo "check Hey from line 2"
        
  - wait: ~
    continue_on_failure: false
  - command: echo "Second command!"
  

  - label: "Second build"
    command: echo "Did we really reaced here? :)"

  

