steps:
  - command: echo 'Tests'
    label: ':hammer:'
  - wait
  - trigger: trigger-deploy
    label: ":ravi:"
    branches: "test"
    async: true
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"
